General:
  OutputFile: "all_pars_on_no_only_no_adapt.root"
  TutorialSamples: ["TutorialConfigs/Samples/SamplePDF_Tutorial.yaml",
                    #"TutorialConfigs/Samples/SamplePDF_Tutorial_ATM.yaml"
                    ]
  FittingAlgorithm: "MCMC"

  RealData: false
  Asimov: true
  CustomReWeight: false
  FakeData: false
  ProcessMCMC: No
  Debug: No
  RandomStart: false
  Seed: 0
  MaCh3Modes: "TutorialConfigs/MaCh3Modes.yaml"
  Fitter:
    FitTestLikelihood: false
  Minuit2:
    NSteps: 400000
  PSO:
    Constriction: 1
    Inertia: 1.
    One: 1.
    Two: 1.
    Particles: 10
    Iterations: 10000
    Convergence: 1.
    TestLikelihoodDim: 9

  MCMC:
    NSteps: 200000
    #KS: Sets how frequent (number of steps) you want to autosave your chain, if you autosave rarely chain will be slightly faster, if you job wall is small you might want more frequent autosave to reduce number of lost steps
    #AutoSave: 500
    AutoSave: 500
    UseReactorConstraint: No
    #Burn in for posterior predictive code
    BurnInSteps: 200000
  Systematics:
    XsecCovName: "xsec_cov"
    XsecFix: [ ]
    XsecCovFile: ["TutorialConfigs/CovObjs/SystematicModel.yaml",
                  #"TutorialConfigs/CovObjs/PCATest.yaml"
                  ]
    XsecPCAThreshold: -1
    XsecPCAParams: [-999, -999]
    XsecStepScale: 0.05

    OscCovName: "osc_cov"
    OscCovFile: [/nfs/scratch0/hwallace/software/MaCh3Tutorial/studies/configs/T2K/OscillationModel_oct_fix_no_only.yaml]
    OscFix: ["baseline", "density", "Ye", "prod_height"]
    OscStepScale: 0.045
    MassOrderFlip: True
    OctantFlip: False


# Prior/Posterior predictive settings
Predictive:
  Ntoy: 10
  #Ntoy: 5000
  #Use Full LLH or only sample contribution based on discussion with Asher we almost always only want the sample likelihood
  FullLLH: false
  PosteriorFiles: "EMPTY"

# LLH Scan settings  
LLHScan:
  # don't make LLH for certain systematic groups
  #LLHScanSkipVector: []
  # Save individual sample contributions to the LLH
  LLHScanBySample: false
  # Number of points we run LLH scans for each systematic
  #LLHScanPoints: 50
  # Number of points for 2D scan in each direction
  #2DLLHScanPoints: 20
  # Add physical ranges for special params whose priors/errors may not be well well-defined
  ScanRanges:
    #delta_cp: [-3.14,3.14]
    
LikelihoodOptions:
  #False means you calculate W2 histogram only during the first reweight, advisable for Barlow-Beeston
  UpdateW2: false
  TestStatistic: "Barlow-Beeston"

AdaptionOptions:
  Settings:
    StartThrow:  10000
    StartUpdate: 1000
    EndUpdate:   100000
    UpdateStep:  1000
    SaveNIterations: 1000
    OutputFileName: mcmc_covariance.root

  Covariance:
    xsec_cov:
      DoAdaption: True
      MatrixBlocks: []
      UseExternalMatrix: False

    osc_cov:
      DoAdaption: True
      MatrixBlocks: []
      UseExternalMatrix: False